services:
  galacticdelivery.api.web:
    image: galacticdelivery.api.web
    build:
      context: .
      dockerfile: GalacticDelivery.Api.Web/Dockerfile
    ports:
      - "5114:8080"
    environment:
      ConnectionStrings__Sqlite: "Data Source=/data/galactice_delivery.sqlite"
    volumes:
      - ./galactice_delivery.sqlite:/data/galactice_delivery.sqlite
